name: attendance_app
description: Swipe-Based Smart Attendance Management System for educational institutions.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API & Networking
  http: ^1.2.1
  dio: ^5.4.3

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.2.2
  local_auth: ^3.0.0

  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7276

  # Card Swiping
  swipeable_card_stack: ^0.0.5

  # Animations & Transitions
  flutter_animate: ^4.5.0
  lottie: ^3.1.0

  # Image Handling
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7

  # PDF Export
  pdf: ^3.10.8
  printing: ^5.11.1

  # Excel Export
  excel: ^4.0.2
  path_provider: ^2.1.2

  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.1.0



  # Swipe experience
  audioplayers: ^5.2.1
  vibration: ^3.1.7
  device_info_plus: ^12.3.0

  # Utilities
  uuid: ^4.3.3
  connectivity_plus: ^7.0.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/sounds/swipe.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf